# Generated by Django 5.2.5 on 2025-08-22 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='is_active',
        ),
        migrations.AddField(
            model_name='poll',
            name='status',
            field=models.CharField(choices=[('c', 'Completed'), ('p', 'Pending'), ('d', 'Deleted'), ('i', 'Invalid')], default='pending', max_length=1),
        ),
    ]
