# Generated by Django 5.2.5 on 2025-08-26 21:49

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0003_alter_pollvote_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='poll',
            options={'ordering': ['created_at'], 'verbose_name_plural': 'Polls'},
        ),
        migrations.AlterModelOptions(
            name='polloption',
            options={'ordering': ['created_at'], 'verbose_name_plural': 'Poll Options'},
        ),
        migrations.AlterModelOptions(
            name='pollvote',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterField(
            model_name='poll',
            name='start_date',
            field=models.DateTimeField(db_default=django.db.models.functions.datetime.Now()),
        ),
        migrations.AlterField(
            model_name='poll',
            name='status',
            field=models.CharField(choices=[('co', 'Completed'), ('pe', 'Pending'), ('ip', 'In Progress'), ('de', 'Deleted'), ('in', 'Invalid')], default='pending', max_length=2),
        ),
    ]
