# Generated by Django 5.2.5 on 2025-08-26 21:49

import datetime
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('society', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_comment='Title of each Task', help_text='Please use less than 255 characters', max_length=255)),
                ('priority', models.SmallIntegerField(choices=[(1, 'low'), (2, 'middle'), (3, 'high'), (4, 'very high')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
            ],
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('a', 'Assigned'), ('u', 'Unassigned'), ('f', 'Finished'), ('n', 'Not Done')], max_length=1)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('assigned_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_assignments', to=settings.AUTH_USER_MODEL)),
                ('finished_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finished_assignments', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.task')),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_comment='Title of each Work-Template.', help_text='Please use less than 255 characters', max_length=255)),
                ('start', models.DateTimeField(default=datetime.datetime(2025, 8, 26, 21, 49, 19, 70414))),
                ('end', models.DateTimeField(default=datetime.datetime(2030, 8, 25, 21, 49, 19, 70414))),
                ('period', models.CharField(choices=[('1d', 'Daily'), ('2d', 'Each 2 Days'), ('1w', 'Weekly'), ('2w', 'Each 2 weeks'), ('1m', 'Monthly'), ('2m', 'Each 2 Month'), ('1y', 'Yearly')], default='1d', max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_infinite', models.BooleanField(default=False)),
                ('duration', models.IntegerField()),
                ('clan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='society.clan')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.work'),
        ),
    ]
