# Generated by Django 5.2.5 on 2025-10-08 16:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='end',
            field=models.DateTimeField(default=datetime.datetime(2030, 10, 7, 16, 57, 38, 446129)),
        ),
        migrations.AlterField(
            model_name='work',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 8, 16, 57, 38, 446129)),
        ),
    ]
