# Generated by Django 5.2.5 on 2025-10-17 13:53

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import job.models
from django.conf import settings
from django.db import migrations, models


def _backfill_task_datetimes(apps, schema_editor):
    from django.utils import timezone
    Task = apps.get_model('job', 'Task')
    now = timezone.now()
    Task.objects.filter(created_at__isnull=True).update(created_at=now)
    Task.objects.filter(updated_at__isnull=True).update(updated_at=now)


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_alter_work_end_alter_work_start'),
        ('society', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_comment='Title of each Task', help_text='Please use less than 255 characters', max_length=255)),
                ('note', models.TextField(blank=True, null=True)),
                ('priority', models.SmallIntegerField(
                    choices=[(1, 'Low'), (2, 'Medium'), (3, 'High'), (4, 'Very High')],
                    default=2,
                    validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)]
                )),
                ('status', models.CharField(choices=[('a', 'Active'), ('d', 'Deleted')], default='a', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('status', models.CharField(choices=[('c', 'Coming'), ('p', 'Progress'), ('f', 'Finished'), ('d', 'Deleted')], default='c', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(model_name='assignment', name='assigned_user'),
        migrations.RemoveField(model_name='assignment', name='finished_by'),
        migrations.RemoveField(model_name='assignment', name='task'),
        migrations.AlterModelOptions(name='work', options={'ordering': ['-start']}),
        migrations.RemoveField(model_name='task', name='work'),
        migrations.RemoveField(model_name='work', name='duration'),
        migrations.AddField(
            model_name='task',
            name='assigned_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_task', to=settings.AUTH_USER_MODEL),
        ),
       
        migrations.AddField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(null=True, blank=True),
        ),
        migrations.AddField(
            model_name='task',
            name='updated_at',
            field=models.DateTimeField(null=True, blank=True),
        ),
       
        migrations.RunPython(_backfill_task_datetimes, migrations.RunPython.noop),
       
        migrations.AlterField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(null=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='updated_at',
            field=models.DateTimeField(null=False),
        ),
        migrations.AddField(
            model_name='task',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='finished_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_task_instances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(
                choices=[('assigned', 'Assigned'), ('finished', 'Finished'), ('delayed', 'Delayed'), ('deleted', 'Deleted')],
                default='assigned',
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name='work',
            name='deadline_duration',
            field=models.PositiveIntegerField(
                db_comment='Each task of this has some deadline duration to be completed ',
                default=2,
                validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.SmallIntegerField(
                choices=[(1, 'Low'), (2, 'Medium'), (3, 'High'), (4, 'Very High')],
                validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)],
            ),
        ),
        migrations.AlterField(model_name='work', name='end', field=models.DateTimeField(default=job.models.IN_FIVE_YEARS)),
        migrations.AlterField(
            model_name='work',
            name='period',
            field=models.CharField(
                choices=[('1d', 'Daily'), ('2d', 'Each 2 Days'), ('1w', 'Weekly'), ('2w', 'Each 2 Weeks'),
                         ('1m', 'Monthly'), ('2m', 'Each 2 Months'), ('1y', 'Yearly')],
                default='1w',
                max_length=2,
            ),
        ),
        migrations.AlterField(model_name='work', name='start', field=models.DateTimeField(default=django.utils.timezone.now)),
        migrations.AddConstraint(
            model_name='work',
            constraint=models.CheckConstraint(condition=models.Q(('end__gte', models.F('start'))), name='work_end_after_start'),
        ),
        migrations.AddField(model_name='tasktemplate', name='work', field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.work')),
        migrations.AddField(model_name='workcycle', name='created_by', field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
        migrations.AddField(model_name='workcycle', name='work', field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.work')),
        migrations.AddField(model_name='task', name='work_cycle', field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='job.workcycle')),
        migrations.DeleteModel(name='Assignment'),
        migrations.AddConstraint(
            model_name='workcycle',
            constraint=models.CheckConstraint(condition=models.Q(('end__gte', models.F('start'))), name='workcycle_end_after_start'),
        ),
    ]
